'use client';
/* oxlint-disable next/no-img-element -- Portfolio photographs are original static assets. */
import {useState} from 'react';
import Link from 'next/link';
import {artworks,type Artwork} from '../artworks/data';
import {Screening} from '../studies/screening';
import './darkroom.css';
export function Darkroom({preview=false}:{preview?:boolean}){
 const[film,setFilm]=useState<Artwork|null>(null);
 const print=(n:number,cls:string,eager=false)=><button className={'dr-print '+cls} aria-label={'Watch '+artworks[n].title} onClick={()=>setFilm(artworks[n])}><span className="dr-print-image"><img src={'/images/'+artworks[n].image} alt={artworks[n].title+' — film image'} loading={preview||eager?'eager':'lazy'}/></span><span className="dr-print-edge" aria-hidden="true"><span>PHILIP DI FIORE</span><span>↗</span></span></button>;
 return <div className={'darkroom'+(preview?' dr-preview':'')} id={preview?undefined:'darkroom-top'}><div className="dr-room"><header className="dr-nav"><a href="#darkroom-top">Philip Di Fiore</a><nav aria-label="Darkroom navigation"><a href="#darkroom-prints">Prints</a><Link href="/catalog">Catalog ↗</Link></nav></header><h1 className="dr-masthead">DI FIORE</h1><section className="dr-opening" id={preview?undefined:'darkroom-prints'}><div className="dr-hero-print">{print(5,'dr-lead-print',true)}<span className="dr-frame-number">01 / 08</span></div><div className="dr-opening-aside"><div><span className="dr-kicker">THE DARKROOM</span><h2>FILMS<br/>& IMAGES</h2></div><div className="dr-aside-bottom"><p>Philip Di Fiore.<br/>Moving pictures.</p><button className="dr-view" onClick={()=>setFilm(artworks[5])}>View film <span>↗</span></button></div></div></section>{!preview&&<><section className="dr-red-spread"><div className="dr-red-aside"><div><span className="dr-kicker">02—03 / 08</span><h2>LIGHT.<br/>SHADOW.</h2></div><div className="dr-small-print">{print(2,'dr-shadow-print')}<span className="dr-frame-number">03 / 08</span></div></div><div>{print(0,'dr-red-print')}<span className="dr-frame-number">02 / 08</span></div></section><section className="dr-color-room"><span className="dr-color-label">04—05 / 08</span><div className="dr-color-main">{print(1,'dr-color-print')}<span className="dr-frame-number">04 / 08</span></div><div className="dr-color-secondary">{print(3,'dr-secondary-print')}<span className="dr-frame-number">05 / 08</span></div><div className="dr-color-word" aria-hidden="true">IMAGE<br/>AFTER<br/>IMAGE.</div></section><section className="dr-contact" id="darkroom-contact"><div className="dr-section-heading"><h2>CONTACT SHEET</h2><span>08 FILMS</span></div><div className="dr-contact-board">{[5,0,2,1,3,4,6,7].map((n,i)=><button className="dr-contact-frame" key={n} onClick={()=>setFilm(artworks[n])} aria-label={'Watch '+artworks[n].title}><span className="dr-contact-photo"><img src={'/images/'+artworks[n].image} alt={artworks[n].title+' — film image'} loading="lazy"/></span><span className="dr-contact-edge"><span>{String(i+1).padStart(2,'0')}</span><span aria-hidden="true">↗</span></span></button>)}</div><p className="dr-contact-note">Philip Di Fiore / Films & images</p></section><footer className="dr-footer"><div><a href="#darkroom-top">Back to the light ↑</a><Link href="/reseda">Original Reseda study ↗</Link></div><p className="dr-masthead" aria-hidden="true">DI FIORE</p></footer></>}</div>{!preview&&<><nav className="study-return dr-return" aria-label="Study navigation"><Link href="/catalog">← All 20</Link><span>20 · Reseda / Darkroom</span><Link href="/reseda">Reseda ↗</Link></nav><Screening work={film} close={()=>setFilm(null)}/></>}</div>;
}
