'use client';
/* oxlint-disable next/no-img-element -- Original portfolio artwork remains local and is the material of these browser studies. */
import {useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {Slider} from '@/components/ui/slider';
import {artworks,type Artwork} from './data';
type Props={preview?:boolean;watch:(work:Artwork)=>void;paused?:boolean};
const img=(work:Artwork)=>'/images/'+work.image;
const initials=[{x:12,y:14,r:-8,w:29,h:62},{x:39,y:5,r:7,w:22,h:53},{x:54,y:30,r:-4,w:28,h:56},{x:28,y:41,r:4,w:20,h:43}];
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export function Palimpsest({watch,preview}:Props){
 const [layers,setLayers]=useState(initials);const [ghosts,setGhosts]=useState<{x:number;y:number;r:number;w:number;h:number;id:number}[]>([]);const [front,setFront]=useState(0);
 const drag=useRef<{i:number;x:number;y:number;sx:number;sy:number;w:number;h:number}|null>(null);const surface=useRef<HTMLDivElement>(null);
 const begin=(e:ReactPointerEvent<HTMLButtonElement>,i:number)=>{const rect=surface.current?.getBoundingClientRect();if(!rect)return; e.currentTarget.setPointerCapture(e.pointerId);drag.current={i,x:e.clientX,y:e.clientY,sx:layers[i].x,sy:layers[i].y,w:rect.width,h:rect.height};setFront(i);setGhosts(g=>[...g.slice(-5),{...layers[i],id:i}]);};
 const move=(e:ReactPointerEvent<HTMLButtonElement>)=>{const d=drag.current;if(!d)return;setLayers(ls=>ls.map((l,i)=>i===d.i?{...l,x:clamp(d.sx+(e.clientX-d.x)/d.w*100,-6,84),y:clamp(d.sy+(e.clientY-d.y)/d.h*100,-8,80)}:l));};
 return <div className="art-stage palimpsest" ref={surface}><span className="art-signature">Philip Di Fiore</span><div className="palimpsest-word" aria-hidden="true">again</div><div className="palimpsest-scar" aria-hidden="true"/>{ghosts.map((g,i)=><img className={'palimpsest-ghost ghost-'+g.id} aria-hidden="true" alt="" key={i} src={img(artworks[[0,2,3,1][g.id]])} style={{left:g.x+'%',top:g.y+'%',width:g.w+'%',height:g.h+'%',transform:`rotate(${g.r}deg)`}}/>)}{layers.map((l,i)=><button key={i} className={'palimpsest-layer layer-'+i} style={{left:l.x+'%',top:l.y+'%',width:l.w+'%',height:l.h+'%',transform:`rotate(${l.r}deg)`,zIndex:front===i?8:3+i}} onPointerDown={e=>begin(e,i)} onPointerMove={move} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onDoubleClick={()=>watch(artworks[[0,2,3,1][i]])} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();setFront(i);setLayers(ls=>ls.map((a,n)=>n===i?{...a,x:clamp(a.x+(e.key==='ArrowRight'?2:e.key==='ArrowLeft'?-2:0),-6,84),y:clamp(a.y+(e.key==='ArrowDown'?2:e.key==='ArrowUp'?-2:0),-8,80)}:a));}if(e.key==='Enter')watch(artworks[[0,2,3,1][i]]);}} aria-label={`${artworks[[0,2,3,1][i]].title}. Drag or use arrow keys to move. Enter to view film.`}><img alt="" src={img(artworks[[0,2,3,1][i]])} draggable={false}/><span>0{i+1} / {artworks[[0,2,3,1][i]].title}</span></button>)}<div className="palimpsest-registration" aria-hidden="true">+<br/><span>+</span></div><div className="art-instruction"><span>Move the layers.</span>{!preview&&<button onClick={()=>watch(artworks[[0,2,3,1][front]])}>{artworks[[0,2,3,1][front]].title} ↗</button>}{!preview&&<button onClick={()=>{setLayers(initials);setGhosts([]);setFront(0);}}>Restore</button>}</div><span className="palimpsest-bottom" aria-hidden="true">what was here / is still here</span></div>;
}
const intervals=[{a:2,w:560,gap:170,y:10,h:340},{a:0,w:330,gap:500,y:-85,h:510},{a:1,w:700,gap:270,y:28,h:400},{a:3,w:360,gap:600,y:-35,h:480},{a:5,w:850,gap:320,y:30,h:330},{a:4,w:460,gap:300,y:-20,h:410}];
export function Interval({watch,preview}:Props){
 const track=useRef<HTMLDivElement>(null);const [progress,setProgress]=useState(0);const drag=useRef<{x:number;start:number}|null>(null);
 useEffect(()=>{if(preview)return;const el=track.current;if(!el)return;const wheel=(e:WheelEvent)=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();el.scrollLeft+=e.deltaY;}};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[preview]);
 const seek=(v:number|readonly number[])=>{const el=track.current;const n=typeof v==='number'?v:v[0];if(el)el.scrollLeft=(el.scrollWidth-el.clientWidth)*n/100;};
 return <div className="art-stage interval"><span className="art-signature">Philip Di Fiore</span><span className="interval-top">a passage in six intervals</span><div className="interval-rule" aria-hidden="true"/><div className="interval-viewport" ref={track} onScroll={()=>{const el=track.current;if(el)setProgress(el.scrollLeft/(el.scrollWidth-el.clientWidth)*100);}} onPointerDown={e=>{if((e.target as HTMLElement).closest('button'))return;drag.current={x:e.clientX,start:e.currentTarget.scrollLeft};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current)e.currentTarget.scrollLeft=drag.current.start+drag.current.x-e.clientX;}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><div className="interval-track"><span className="interval-start" aria-hidden="true">I.</span>{intervals.map((f,i)=><figure key={i} style={{width:f.w,marginRight:f.gap,transform:`translateY(${f.y}px)`,height:f.h}}><img src={img(artworks[f.a])} alt={artworks[f.a].title} draggable={false}/><figcaption><button onClick={()=>watch(artworks[f.a])}>{String(i+1).padStart(2,'0')} — {artworks[f.a].title} ↗</button><span>{artworks[f.a].artist}</span></figcaption>{i===1&&<span className="interval-word">and then,<br/>nothing.</span>}{i===3&&<span className="interval-word">a little<br/>further.</span>}</figure>)}<span className="interval-end">…</span></div></div><div className="interval-position"><span>{String(Math.round(progress)).padStart(3,'0')}</span><div><Slider min={0} max={100} step={.1} value={[progress]} onValueChange={seek} aria-label="Position in the film passage"/></div><span>Travel sideways →</span></div></div>;
}
const words=[{a:1,c:'word-stranger',text:'Stranger.'},{a:0,c:'word-friend',text:'Old friend.'},{a:5,c:'word-call',text:'If you call,'},{a:2,c:'word-spell',text:'warm spell.'},{a:4,c:'word-runnin',text:'Runnin’'},{a:6,c:'word-game',text:'Game gets old.'}];
export function Sentence({watch,preview}:Props){const [active,setActive]=useState(1);return <div className="art-stage sentence"><span className="art-signature">Philip Di Fiore</span><span className="sentence-punctuation" aria-hidden="true">(</span><img className="sentence-image" key={active} src={img(artworks[active])} alt={artworks[active].title}/><div className="sentence-text">{words.map(w=><button key={w.a} className={w.c+(active===w.a?' is-spoken':'')} onPointerEnter={()=>setActive(w.a)} onFocus={()=>setActive(w.a)} onClick={()=>setActive(w.a)}>{w.text}</button>)}</div><span className="sentence-footnote">a sentence made of films<br/>read in any order</span><span className="sentence-end" aria-hidden="true">)</span>{!preview&&<button className="sentence-index" onClick={()=>watch(artworks[active])}>{artworks[active].title} ↗</button>}</div>;}
const fragments=[{x:4,y:8,w:26,h:50,a:0,r:0},{x:30,y:8,w:16,h:26,a:3,r:0},{x:46,y:3,w:29,h:36,a:2,r:0},{x:75,y:8,w:20,h:60,a:1,r:0},{x:14,y:59,w:25,h:31,a:4,r:0},{x:39,y:35,w:21,h:58,a:5,r:0},{x:60,y:40,w:14,h:42,a:7,r:0},{x:74,y:70,w:21,h:21,a:6,r:0}];
export function Chance({watch,preview}:Props){const [pieces,setPieces]=useState(fragments.map(p=>({...p,missing:false})));const[count,setCount]=useState(0);const[history,setHistory]=useState('The first arrangement.');const operate=(kind:'exchange'|'rotate'|'absence')=>{setPieces(ps=>{const next=ps.map(p=>({...p}));const a=1+(count*3)%7;const b=1+(count*3+2)%7;if(kind==='exchange'){[next[a].a,next[b].a]=[next[b].a,next[a].a];}if(kind==='rotate')next[a].r=(next[a].r+90)%360;if(kind==='absence')next[a].missing=!next[a].missing;return next;});setCount(n=>n+1);setHistory(kind==='exchange'?'Two fragments exchange places.':kind==='rotate'?'One fragment turns.':'One fragment changes its presence.');};return <div className="art-stage chance"><span className="art-signature">Philip Di Fiore</span><span className="chance-marker" aria-hidden="true">{String(count).padStart(3,'0')}</span><div className="chance-collage">{pieces.map((p,i)=><div className={'chance-fragment fragment-'+i+(p.missing?' missing':'')} key={i} style={{left:p.x+'%',top:p.y+'%',width:p.w+'%',height:p.h+'%'}}><img src={img(artworks[p.a])} alt={artworks[p.a].title} style={{transform:`rotate(${p.r}deg) scale(${p.r%180?1.55:1})`}}/>{!p.missing&&<button onClick={()=>watch(artworks[p.a])} aria-label={'View '+artworks[p.a].title}><span aria-hidden="true">↗</span></button>}{i===0&&<span className="chance-constant">this fragment stays.</span>}</div>)}<span className="chance-line" aria-hidden="true"/></div><div className="chance-controls"><span className="chance-live" aria-live={preview?'off':'polite'}>{history}</span><div><button onClick={()=>operate('exchange')}>Exchange</button><button onClick={()=>operate('rotate')}>Rotate</button><button onClick={()=>operate('absence')}>Absence</button><button className="chance-reset" onClick={()=>{setPieces(fragments.map(p=>({...p,missing:false})));setCount(0);setHistory('The first arrangement.');}}>Restore</button></div></div></div>;}
export function Afterimage({watch,preview}:Props){
 const [traces,setTraces]=useState<{x:number;y:number;a:number;id:number;r:number}[]>([]);const [current,setCurrent]=useState(0);const [resting,setResting]=useState(true);const surface=useRef<HTMLDivElement>(null);const last=useRef(0);const tick=useRef(0);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const trace=(e:ReactPointerEvent<HTMLDivElement>)=>{if(preview||((e.target as HTMLElement).closest('button')))return;const now=Date.now();if(now-last.current<140)return;last.current=now;const rect=surface.current?.getBoundingClientRect();if(!rect)return;const a=tick.current%artworks.length;tick.current++;setCurrent(a);setResting(false);setTraces(t=>[...t.slice(-11),{x:(e.clientX-rect.left)/rect.width*100,y:(e.clientY-rect.top)/rect.height*100,a,id:tick.current,r:(tick.current%5-2)*7}]);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setResting(true),1250);};
 return <div className="art-stage afterimage" ref={surface} onPointerMove={trace} onPointerDown={trace}><span className="art-signature">Philip Di Fiore</span><div className="afterimage-field" aria-hidden="true">{(preview?[{x:37,y:43,a:0,id:1,r:-9},{x:53,y:51,a:1,id:2,r:5},{x:61,y:37,a:2,id:3,r:-4}]:traces).map(t=><img key={t.id} className="afterimage-trace" src={img(artworks[t.a])} alt="" style={{left:t.x+'%',top:t.y+'%',transform:`translate(-50%,-50%) rotate(${t.r}deg)`}}/>)}</div><div className={'afterimage-rest '+(resting?'visible':'')} key={resting?current:-1}><img src={img(artworks[current])} alt={artworks[current].title}/></div><div className="afterimage-type" aria-hidden="true">after<br/><em>image</em></div><button className="afterimage-current" onClick={()=>watch(artworks[current])}>{artworks[current].title} <span>↗</span></button><div className="afterimage-bottom"><span>Move. Then be still.</span><button onClick={()=>{setCurrent(a=>(a+1)%artworks.length);setResting(true);}}>Next image</button></div></div>;
}
export function Polyphony({watch,preview,paused}:Props){const[motion,setMotion]=useState(false);const [hold,setHold]=useState(false);const indices=[2,0,1,3,4,5];return <div className={'art-stage polyphony'+(hold||paused?' score-held':'')}><span className="art-signature">Philip Di Fiore</span><div className="polyphony-score">{indices.map((a,i)=><div className={'polyphony-channel channel-'+i} key={a}><img src={img(artworks[a])} alt={artworks[a].title}/>{motion&&!preview&&<iframe src={`https://player.vimeo.com/video/${artworks[a].vimeo}?background=1&autoplay=1&muted=1&loop=1&title=0&byline=0&portrait=0`} title="Silent film channel" allow="autoplay; fullscreen" tabIndex={-1}/>}<div className="channel-shade"/><button className="channel-label" onClick={()=>watch(artworks[a])}><span>0{i+1}</span><span>{artworks[a].title} ↗</span></button></div>)}<div className="polyphony-cross" aria-hidden="true">+</div></div><div className="polyphony-bottom"><span>six channels / no center</span><div><button onClick={()=>setHold(h=>!h)}>{hold?'Resume the score':'Hold the score'}</button><button onClick={()=>setMotion(m=>!m)}>{motion?'Return to stills':'Start motion'}</button></div></div>{motion&&!preview&&<span className="polyphony-silent">six films playing silently</span>}</div>;}
export const works=[Palimpsest,Interval,Sentence,Chance,Afterimage,Polyphony];
