'use client';
/* oxlint-disable next/no-img-element -- Original portfolio imagery is served as static local assets. */
import {useState} from 'react';
import Link from 'next/link';
import {artworks,type Artwork} from '../artworks/data';
import {Screening} from './screening';
import './beautiful.css';
import {beautyStudies} from './data';
type Props={kind:number;preview?:boolean};
export function BeautifulComposition({kind,preview=false}:Props){const[film,setFilm]=useState<Artwork|null>(null);
 const frame=(i:number,cls:string,eager=false)=><button className={'beauty-image '+cls} onClick={()=>setFilm(artworks[i])} aria-label={'Watch '+artworks[i].title}><img src={'/images/'+artworks[i].image} alt={artworks[i].title+' — film still'} loading={preview||eager?'eager':'lazy'}/><span className="beauty-play" aria-hidden="true">↗</span></button>;
 const signature=(dark=false)=><header className={'beauty-signature'+(dark?' light':'')}><span>PHILIP DI FIORE</span><span>FILMS & IMAGES</span></header>;
 return <div className={'beauty beauty-'+beautyStudies[kind].slug+(preview?' beauty-preview':'')}>
 {kind===0&&<><section className="beauty-scene vermilion-first">{signature()}{frame(0,'vermilion-face',true)}<div className="vermilion-violet" aria-hidden="true"/><h1 className="vermilion-name">Philip<br/><em>Di Fiore.</em></h1>{frame(5,'vermilion-small',true)}<span className="beauty-corner">MOVING PICTURES / I</span></section>{!preview&&<><section className="vermilion-second">{frame(1,'vermilion-portrait')}<span className="vermilion-mark" aria-hidden="true">f.</span>{frame(2,'vermilion-shadow')}</section><section className="vermilion-third">{frame(4,'vermilion-crowd')}{frame(3,'vermilion-buffalo')}</section></>}</>}
 {kind===1&&<><section className="beauty-scene chapel-first">{signature(true)}<h1 className="chapel-name">Philip Di Fiore</h1><div className="chapel-triptych">{frame(2,'chapel-left',true)}{frame(5,'chapel-center',true)}{frame(6,'chapel-right',true)}</div><span className="chapel-foot">LIGHT / SOUND / SHADOW</span></section>{!preview&&<><section className="chapel-solitary"><span className="chapel-rule"/>{frame(1,'chapel-color')}<span className="chapel-rule"/></section><section className="chapel-pair">{frame(0,'chapel-red')}{frame(7,'chapel-miko')}</section></>}</>}
 {kind===2&&<><section className="beauty-scene silver-first"><header className="silver-signature">Philip Di Fiore <span>Moving images</span></header>{frame(5,'silver-main',true)}{frame(2,'silver-small',true)}<h1 className="silver-name">A body<br/><em>of images.</em></h1><span className="silver-margin">PHILIP DI FIORE — PLATE I</span><span className="silver-page">01</span></section>{!preview&&<><section className="silver-spread">{frame(1,'silver-color')}<div className="silver-footnote">Color plate.<br/>A film in eight images.</div>{frame(6,'silver-side')}</section><section className="silver-end">{frame(0,'silver-red')}<span>Philip Di Fiore</span></section></>}</>}
 {kind===3&&<><section className="beauty-scene frieze-first">{signature()}<h1 className="frieze-name">Di Fiore<span>PHILIP</span></h1><div className="frieze-strips">{[1,0,2,5,4,7,3].map((n,i)=><div className={'frieze-strip strip-'+i} key={n}>{frame(n,'',true)}</div>)}</div><div className="frieze-base"><span>FILMS, IN COLOR.</span><span>—</span><span>IMAGES, IN TIME.</span></div></section>{!preview&&<><section className="frieze-spread">{frame(0,'frieze-red')}{frame(5,'frieze-silver')}<div className="frieze-block" aria-hidden="true"/>{frame(1,'frieze-violet')}</section><section className="frieze-full">{frame(3,'frieze-last')}</section></>}</>}
 {kind===4&&<><section className="beauty-scene violet-first">{signature()}<div className="violet-circle">{frame(0,'',true)}</div><div className="violet-square" aria-hidden="true"/>{frame(5,'violet-photo',true)}<h1 className="violet-name">Philip<br/><em>Di Fiore</em></h1><span className="violet-small">AN ARRANGEMENT OF IMAGES</span></section>{!preview&&<><section className="violet-second">{frame(1,'violet-portrait')}<div className="violet-disc" aria-hidden="true"/>{frame(2,'violet-dark')}</section><section className="violet-third">{frame(3,'violet-landscape')}{frame(7,'violet-detail')}</section></>}</>}
 {kind===5&&<><section className="beauty-scene lacquer-first">{signature()}<h1 className="lacquer-name">Philip<br/><em>Di Fiore</em></h1><div className="lacquer-screen">{[1,2,0].map((n,i)=><div className={'lacquer-panel panel-'+i} key={n}>{frame(n,'',true)}</div>)}</div><span className="lacquer-seal" aria-hidden="true">DF</span><span className="lacquer-foot">A COLLECTION OF FILMS & IMAGES</span></section>{!preview&&<><section className="lacquer-second">{frame(5,'lacquer-silver')}<div className="lacquer-ink" aria-hidden="true"/>{frame(7,'lacquer-night')}</section><section className="lacquer-third">{frame(3,'lacquer-color')}<span className="lacquer-endword">Di Fiore</span></section></>}</>}
 {!preview&&<><footer className="beauty-footer"><span>Philip Di Fiore</span><span>Films & images</span><Link href="/catalog">Catalog ↗</Link></footer><nav className="study-return" aria-label="Study navigation"><Link href="/catalog">← All 19</Link><span>{String(kind+14).padStart(2,'0')} · {beautyStudies[kind].name}</span><Link href={'/studies/'+beautyStudies[(kind+1)%6].slug}>Next →</Link></nav><Screening work={film} close={()=>setFilm(null)}/></>}
 </div>;
}
