'use client';
/* oxlint-disable next/no-img-element -- Preview compositions use the artist's original static assets. */
import Link from 'next/link';
import {BeautifulComposition} from '../studies/beautiful';
import {beautyStudies} from '../studies/data';
import {CollectionOnePreview} from '../collection-one/page';
import {works} from '../artworks/works';
import {studies} from '../artworks/data';
import '../artworks/art.css';
import '../reseda/reseda.css';
import './catalog.css';
const first=['After Dark','The Director’s Journal','Strange Frequencies','Cut to Color','Film Atlas','Electric Auteur'];
const noop=()=>{};
function Plate({children,href,no,name,material,old=false}:{children:React.ReactNode;href:string;no:number;name:string;material?:string;old?:boolean}){return <article className="catalog-plate"><div className="catalog-preview"><div className={'catalog-preview-inner'+(old?' preview-inner':'')} aria-hidden="true" inert>{children}</div></div><Link href={href} aria-label={'Open study '+no+': '+name}><div className="catalog-caption"><span>{String(no).padStart(2,'0')}</span><h3>{name}</h3><span>↗</span></div>{material&&<p className="catalog-material">{material}</p>}</Link></article>;}
export default function Catalog(){return <main className="catalog"><header className="catalog-header"><span>PHILIP DI FIORE</span><nav aria-label="Catalog collections"><a href="#new">Six new</a><a href="#reseda">Reseda</a><a href="#preserved">Previous twelve</a></nav></header><section className="catalog-intro"><div><span className="catalog-overline">A CATALOG OF POSSIBILITIES</span><h1>Nineteen ways<br/><em>to be seen.</em></h1></div><p>Studies for an artist’s website.<br/>The newest six explore beauty<br/>through the composition itself.</p></section><section className="catalog-group" id="new"><div className="catalog-group-heading"><h2>III / The composed image</h2><span>14—19 · NEW</span></div><div className="catalog-grid">{beautyStudies.map((s,i)=><Plate key={s.slug} href={'/studies/'+s.slug} no={i+14} name={s.name} material={s.material}><BeautifulComposition kind={i} preview/></Plate>)}</div></section><section className="catalog-group catalog-reseda-group" id="reseda"><div className="catalog-group-heading"><h2>A study after Reseda</h2><span>13 · TEMPLATE STUDY</span></div><div className="catalog-reseda-layout"><Plate href="/reseda" no={13} name="Reseda" material="Monumental type / quiet rules / tall image plates"><div className="reseda-study"><header className="reseda-nav"><span>Philip Di Fiore</span><span>Images</span></header><p className="reseda-wordmark">DI FIORE</p><div className="reseda-lead"><div className="reseda-image"><img src="/images/strangernew.jpg" alt=""/></div><div className="reseda-lead-copy"><h2>FILMS<br/>& IMAGES</h2><div><p>A selection of moving pictures.<br/>Philip Di Fiore.</p><span className="reseda-outline">View film ↗</span></div></div></div></div></Plate><div className="catalog-reseda-note"><p>Wide lettering.<br/>Thin lines.<br/>Room for the images.</p><a href="https://www.squarespace.com/templates/reseda-fluid-demo" target="_blank" rel="noreferrer">The Reseda reference ↗</a></div></div></section><section className="catalog-group" id="preserved"><div className="catalog-group-heading"><h2>II / The browser as medium</h2><span>07—12 · PRESERVED</span></div><div className="catalog-grid">{studies.map((s,i)=>{const C=works[i];return <Plate key={s.title} href={'/collection-two?room='+(i+1)} no={i+7} name={s.title} material={s.material}><C watch={noop} preview/></Plate>;})}</div></section><section className="catalog-group"><div className="catalog-group-heading"><h2>I / The first directions</h2><span>01—06 · PRESERVED</span></div><div className="catalog-grid">{first.map((name,i)=><Plate key={name} href={'/collection-one?concept='+(i+1)} no={i+1} name={name} old><CollectionOnePreview index={i}/></Plate>)}</div></section><footer className="catalog-footer"><span>Philip Di Fiore / Website studies</span><span>19 directions. All previous collections preserved.</span></footer></main>;}
